### ISSUE TITLE
Release 3.0.3 with Rails 5.1 support to Rubygems

### ISSUE THREAD

**Issue by norman** [FooBarWidget/default_value_for#71] opened 2017-07-03 14:57 UTC
@FooBarWidget Can you please sign and release a new gem with the recent changes? Thanks!

**Comment by norman** [comment] 2017-08-16 13:24
@FooBarWidget it would be great to finally get a new version out, could you please sign and release the gem soon?

**Comment by joshRpowell** [comment] 2017-09-04 21:43
@FooBarWidget any update on signing & releasing the gem?

**Comment by FooBarWidget** [comment] 2017-09-05 05:45
Woops sorry, somehow this email got lost in my inbox.

Gem signing is no longer necessary because the Ruby OpenGPG gem signing project has shut down and there are no alternatives that have traction.

@norman I've added norman@njclarke.com to the list of gem owners. You should be able to push the gem yourself from now on. Let me know if it's not working.

**Comment by chrisarcand** [comment] 2017-09-13 14:18
@norman Mind looking in to this again?

**Comment by chrisarcand** [comment] 2017-09-13 14:22
@norman Could you also tag a release?

I'm happy to help maintain and release this gem with the right permissions, by the way.

**Comment by IgorDobryn** [comment] 2017-10-02 16:37
@norman any updates on releasing the gem?

**Comment by FooBarWidget** [comment] 2017-10-02 17:03
@chrisarcand I've given you push rights too.

**Comment by chrisarcand** [comment] 2017-10-02 17:04
Thanks @FooBarWidget, much appreciated. 💙  I'll tend to this later today.

**Comment by chrisarcand** [comment] 2017-10-02 18:25
@FooBarWidget Sorry to bother one more time - I'll need GitHub write permissions to this repository to properly tag a 3.0.3 release, close this issue, etc.

I'll also handle any regressions or future minor maintenance concerns, especially for as long as my team at @manageiq utilizes this dependency.

Thanks!

**Comment by FooBarWidget** [comment] 2017-10-02 20:43
I've added you now.

**Comment by chrisarcand** [comment] 2017-10-02 20:57
:shipit: [Version 3.0.3](https://github.com/FooBarWidget/default_value_for/releases/tag/release-3.0.3) has been [released to RubyGems](https://rubygems.org/gems/default_value_for/versions/3.0.3)

🎉 Thanks everyone

**Closed by chrisarcand** 2017-10-02 20:57 UTC

**Comment by IgorDobryn** [comment] 2017-10-03 06:57
@chrisarcand, thank you!
